services:
  db:
    image: postgres:18
    container_name: diaspora-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: Diaspora
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  pgadmin:
    image: dpage/pgadmin4:9.8
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_REPLACE_SERVERS_ON_STARTUP: "True"
    volumes:
      - ./servers.json:/pgadmin4/servers.json:ro
      - ./.pgpass:/tmp/pgpass:ro
    depends_on:
      - db

  client-api:
    build:
      context: ../../src/Web/Client.Api
    container_name: diaspora-client-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5220:8080"
    depends_on:
      - db

  spa:
    build:
      context: ../../src/Web/Client.Api/spa
    container_name: diaspora-spa
    ports:
      - "5173:8080"
    depends_on:
      - client-api

volumes:
  postgres_data: